services:
  app:
    container_name: shortq-app
    restart: unless-stopped
    ports: !override
      - "127.0.0.1:${SHORTQ_PORT:-8000}:8080"
  db:
    container_name: shortq-postgres
    restart: unless-stopped
