package db

import (
	"context"
	"database/sql"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
)

func Open(dsn string) (*sql.DB, error) {
	database, err := sql.Open("pgx", dsn)
	if err != nil {
		return nil, err
	}
	database.SetMaxOpenConns(20)
	database.SetMaxIdleConns(5)
	database.SetConnMaxLifetime(time.Hour)
	var pingErr error
	for i := 0; i < 30; i++ {
		if pingErr = database.Ping(); pingErr == nil {
			return database, nil
		}
		time.Sleep(2 * time.Second)
	}
	database.Close()
	return nil, pingErr
}

func Migrate(database *sql.DB) error {
	ctx := context.Background()
	conn, err := database.Conn(ctx)
	if err != nil {
		return err
	}
	defer conn.Close()
	if _, err = conn.ExecContext(ctx, `SELECT pg_advisory_lock(hashtext('shortq_schema_migrate'))`); err != nil {
		return err
	}
	defer conn.ExecContext(ctx, `SELECT pg_advisory_unlock(hashtext('shortq_schema_migrate'))`)

	statements := []string{
		`CREATE TABLE IF NOT EXISTS tenants (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(140) NOT NULL, slug VARCHAR(80) NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS tenant_domains (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, domain VARCHAR(190) NOT NULL UNIQUE, status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active')), verification_token VARCHAR(80) NOT NULL, not_found_url TEXT, verified_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id BIGINT REFERENCES tenants(id) ON DELETE SET NULL, email VARCHAR(190) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, role VARCHAR(16) NOT NULL DEFAULT 'customer' CHECK (role IN ('superadmin','tenant','customer')), deletion_access BOOLEAN NOT NULL DEFAULT FALSE, active BOOLEAN NOT NULL DEFAULT TRUE, password_hash BYTEA NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS audit_events (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL, actor_email VARCHAR(190) NOT NULL DEFAULT '', auth_type VARCHAR(24) NOT NULL, action VARCHAR(80) NOT NULL, target_type VARCHAR(40) NOT NULL, target_id VARCHAR(255) NOT NULL DEFAULT '', outcome VARCHAR(16) NOT NULL CHECK (outcome IN ('success','denied')), before_json JSONB, after_json JSONB, ip_address VARCHAR(64) NOT NULL DEFAULT '', user_agent VARCHAR(500) NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS password_resets (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash CHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, used_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS api_keys (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, name VARCHAR(120) NOT NULL, key_hash CHAR(64) NOT NULL UNIQUE, prefix VARCHAR(24) NOT NULL, scope VARCHAR(16) NOT NULL DEFAULT 'account' CHECK (scope IN ('account','user')), last_used_at TIMESTAMPTZ, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS links (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, tenant_id BIGINT REFERENCES tenants(id) ON DELETE SET NULL, slug VARCHAR(80) NOT NULL UNIQUE, target_url TEXT NOT NULL, title VARCHAR(180) NOT NULL DEFAULT '', visibility VARCHAR(16) NOT NULL DEFAULT 'private' CHECK (visibility IN ('private','department')), clicks BIGINT NOT NULL DEFAULT 0, redirect_code SMALLINT NOT NULL DEFAULT 302, expires_at TIMESTAMPTZ, max_clicks BIGINT, expired_url TEXT, ios_url TEXT, android_url TEXT, password_hash BYTEA, forward_query BOOLEAN NOT NULL DEFAULT TRUE, utm_source VARCHAR(255) NOT NULL DEFAULT '', utm_medium VARCHAR(255) NOT NULL DEFAULT '', utm_campaign VARCHAR(255) NOT NULL DEFAULT '', utm_term VARCHAR(255) NOT NULL DEFAULT '', utm_content VARCHAR(255) NOT NULL DEFAULT '', tags_json TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMPTZ)`,
		`CREATE TABLE IF NOT EXISTS clicks (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, link_id BIGINT NOT NULL REFERENCES links(id) ON DELETE CASCADE, ip VARCHAR(64) NOT NULL, user_agent TEXT NOT NULL, referrer TEXT NOT NULL, country_code CHAR(2) NOT NULL DEFAULT '', method VARCHAR(10) NOT NULL DEFAULT 'GET', status_code SMALLINT NOT NULL DEFAULT 302, resolved_url TEXT, route_type VARCHAR(24) NOT NULL DEFAULT 'default', browser VARCHAR(80) NOT NULL DEFAULT '', os VARCHAR(80) NOT NULL DEFAULT '', device VARCHAR(32) NOT NULL DEFAULT '', is_bot BOOLEAN NOT NULL DEFAULT FALSE, referrer_host VARCHAR(255) NOT NULL DEFAULT '', utm_source VARCHAR(255) NOT NULL DEFAULT '', utm_medium VARCHAR(255) NOT NULL DEFAULT '', utm_campaign VARCHAR(255) NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE TABLE IF NOT EXISTS link_geo_targets (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, link_id BIGINT NOT NULL REFERENCES links(id) ON DELETE CASCADE, country_code CHAR(2) NOT NULL, target_url TEXT NOT NULL, UNIQUE(link_id,country_code))`,
		`CREATE TABLE IF NOT EXISTS click_rollups_daily (day DATE NOT NULL, link_id BIGINT NOT NULL REFERENCES links(id) ON DELETE CASCADE, country_code CHAR(2) NOT NULL DEFAULT '', device VARCHAR(32) NOT NULL DEFAULT '', browser VARCHAR(80) NOT NULL DEFAULT '', referrer_host VARCHAR(255) NOT NULL DEFAULT '', utm_campaign VARCHAR(255) NOT NULL DEFAULT '', route_type VARCHAR(24) NOT NULL DEFAULT '', status_code SMALLINT NOT NULL DEFAULT 0, clicks BIGINT NOT NULL DEFAULT 0, PRIMARY KEY(day,link_id,country_code,device,browser,referrer_host,utm_campaign,route_type,status_code))`,
		`CREATE TABLE IF NOT EXISTS schema_migrations (version BIGINT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
		`CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_events(id,created_at)`, `CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_events(actor_user_id,id)`, `CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_events(action,id)`, `CREATE INDEX IF NOT EXISTS idx_audit_target ON audit_events(target_type,id)`, `CREATE INDEX IF NOT EXISTS idx_audit_outcome ON audit_events(outcome,id)`,
		`CREATE INDEX IF NOT EXISTS idx_links_tenant_id ON links(tenant_id,id)`, `CREATE INDEX IF NOT EXISTS idx_links_user_id ON links(user_id,id)`, `CREATE INDEX IF NOT EXISTS idx_links_visibility ON links(tenant_id,visibility,deleted_at,id)`, `CREATE INDEX IF NOT EXISTS idx_clicks_created_at ON clicks(created_at)`, `CREATE INDEX IF NOT EXISTS idx_clicks_link_created ON clicks(link_id,created_at)`, `CREATE INDEX IF NOT EXISTS idx_clicks_country_created ON clicks(country_code,created_at,id)`, `CREATE INDEX IF NOT EXISTS idx_clicks_device_created ON clicks(device,created_at,id)`, `CREATE INDEX IF NOT EXISTS idx_domains_tenant_active ON tenant_domains(tenant_id,status,verified_at,id)`, `CREATE INDEX IF NOT EXISTS idx_rollups_link_day ON click_rollups_daily(link_id,day)`,
		`INSERT INTO schema_migrations(version) VALUES(1),(2),(3),(4) ON CONFLICT(version) DO NOTHING`,
	}
	tx, err := conn.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	for _, statement := range statements {
		if _, err := tx.ExecContext(ctx, statement); err != nil {
			return err
		}
	}
	return tx.Commit()
}
